### ISSUE TITLE
Extra Rigidbody inside the scene

### ISSUE THREAD

**Issue by LenHu404** [JirkaDellOro/Prima#57]
There is an extra Rigidbody in my scene. 

It can be removed by Collisionhandling and and then removing of the Component Rigidbody. 
But by doing so, there are problems with spawning new Nodes with Rigidbodys.

**Comment by JirkaDellOro** [comment]
Where can I find your project?

**Comment by LenHu404** [comment]
Github: https://github.com/LenHu404/primaWS2021/tree/main/projects/ForestRun
Githu-Pages: https://lenhu404.github.io/primaWS2021/projects/ForestRun/index.html

You can spawn new Objects by pressing E.

**Comment by JirkaDellOro** [comment]
Hm, I can think of a cause. Since you load graphs with rigidbodies, those rigidbodies are created when deserializing the graph structure and placed in the physics world. Though they should only be created when a graph instance is created. I'll look into that.

**Comment by JirkaDellOro** [comment]
Can you continue working like that for a while or do you need a quickfix/workaround?

**Comment by LenHu404** [comment]
Yesi think i can work around that for a while.

**Comment by UmbertoFalkenhagen** [comment]
Hey, I just wanted to add more information since I have the same issue. When I continued the game, I noticed also that even though the objects are removed from my scene when restarting, the rigidbodies stayed. I attached a screenshot that was taken after 3 respawns in my scene. It shows how the rigid bodies of already removed objects stay in the scene (and stay interactive, meaning I can run into them and die) It should be noted that my game doesn't reload the scene when restarting but only resets the player to the origin of the world and removes all old platforms and ground segments.

![Bug_Rigidbodies_Fudge](https://user-images.githubusercontent.com/48802310/149966557-8d7cf9ae-02db-48e5-9d51-c6c0ee0a39d5.png)

**Comment by JirkaDellOro** [comment]
That's a different problem. Remove the ComponentRigidbody before you remove a node, as Lennard did or clear the physics world completely when restarting. Try `ƒ.Physics.initializePhysics();`

**Comment by JirkaDellOro** [comment]
So, ich habe etwas herumgefixed. Schaut mal bitte, ob so alles für euch zunächst funktioniert, lasst den Issue aber offen. Ich denke, ich muss das noch sauberer machen.

So I fixed a bit.  Please check, if this suits your needs, but keep the issue open. There's some things I need to do cleaner.

Notes:
RB is placed in the world when render initializes Component. Removed, when component gets removed -> isInitialized is set to false. Check if multiple physics worlds should exists for different graphs!
